num_workers: 4
seed: 1234
lr_decay_step: 500
# dataset: zinc_complex3a6p_data_smiles
dataset: zinc_complex3a6p_data
data_dir: '/public/home/hpc192311018/Huabei/project/smtar-rna/project/data/4z4d/dataset'
log_dir: '/public/home/hpc192311018/Huabei/project/smtar-rna/project/log/tune/4z4d_molecule_gnn_super_gamma'
model_name: molecular_gnn_super_gamma
loss: mse
# weight_decay: 0.0001
tune: True
# in_channels: 483
in_channels: 10
out_channels: 1
gpus: 1
max_epochs: 500
# lr_decay_min_lr: 1e-5
enable_progress_bar: False
