
# checkpoint
#load_dir: checkpoints/gcn
# lr
lr_scheduler: cosine
lr_decay_steps: 100
lr: 0.0005
lr_decay_min_lr: 1e-5
lr_decay_rate: 0.99

# data
dataset: zinc_complex3a6p_data
data_dir: 'data/4z4d/dataset'
log_dir: 'log/4z4d/molecule_gnn'
model_name: molecular_gnn_super_gamma

# train
max_epochs: 500
gpus: 1
#project: gcn_3a6p
in_channels: 10
hidden_channels: 256
out_channels: 1
hidden_layers: 6
out_layers: 6
loss: mse
project: 4z4d_molecule_gnn_super_gamma
