
# This is a template config file for the project. It is used to generate the config file for each run.
project: egnn_large
comment: multilable_little_large
group: ~
tune: False
seed: 1234
wandb: True
early_stop:
  monitor: val_loss
  patience: 100

# 训练配置
trainer:
  init:
    accelerator: gpu
    devices: 1
    precision: 32
    fast_dev_run: False
    max_epochs: 62
    enable_progress_bar: True
    enable_model_summary: True
    enable_checkpointing: True

  fit:
    # 从中断的地方继续训练
    ckpt_path: ~

# 数据模块配置
pl_data_module:
  dataset: 'zinc_complex3a6p_data'
  data_dir: 'data/dataset/dataset/3a6p_100w'
  batch_size: 64
  num_workers: 4

# 模型配置
pl_module:
  weight_decay: 0
  loss: 'smooth_l1'
  model_name: 'egnn_multilable'

  # optimizer
  lr: 5.e-4
  lr_decay_min_lr: 0
  lr_scheduler: 'cosine_warmup'
  # cosine_warmup
  lr_t_0: 2
  lr_t_mult: 2
  # cosine
  lr_t_max: 10
  # step
  lr_decay_steps: 1
  lr_decay_rate: 0.9
  
  model:
    in_node_nf: 11
    hidden_nf: 96
    out_node_nf: 5
    n_layers: 4
    attention: True
    normalize: False
    tanh: False
