

project: test
comment: comment
tune: False
seed: 1234
# wandb: False
early_stop:
  monitor: val_loss
  patience: 5

# log_dir: 'log/'
trainer:
  accelerator: gpu
  devices: 1
  fast_dev_run: False
  max_epochs: 100
  resume_from_checkpoint: ~
  auto_lr_find: False
  auto_scale_batch_size: False

pl_data_module:
  dataset: 'zinc_complex3a6p_data'
  data_dir: 'data/3a6p/zinc_drug_like_100k/3a6p_pocket5_202020'
  batch_size: 1024
  num_workers: 8

pl_module:
  weight_decay: 0
  loss: 'mse'
  model_name: 'molecular_gnn_super_gamma'
  lr: 5.e-4
  lr_scheduler: 'cosine'
  lr_decay_steps: 5
  lr_decay_rate: 0.99
  lr_decay_min_lr: 1.e-5

  model:
    input_dim: 10
    hidden_dim: 256
    output_dim: 1
    hidden_layers: 10
    out_layers: 6
